"""recordings, raw chunk v2, marker sources, label tiers

Revision ID: 5e144fc9d453
Revises: d1c0cc763b9e
Create Date: 2026-10-06 16:07:56.151242
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '5e144fc9d453'
down_revision = 'd1c0cc763b9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_uid', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('provenance', sa.String(length=24), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=True),
    sa.Column('sampling_config', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('integrity', sa.JSON(), nullable=True),
    sa.Column('integrity_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recording_uid'),
    sa.UniqueConstraint('session_id')
    )
    with op.batch_alter_table('sensor_sample_chunks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_t0', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('firmware_version', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('packet_log', sa.JSON(), nullable=True))

    with op.batch_alter_table('session_labels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tier', sa.String(length=8), server_default='SILVER', nullable=False))
        batch_op.add_column(sa.Column('confirmed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_foreign_key('fk_session_labels_confirmed_by_users', 'users', ['confirmed_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('session_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kind', sa.String(length=32), server_default='note', nullable=False))
        batch_op.add_column(sa.Column('source', sa.String(length=8), server_default='USER', nullable=False))
        batch_op.add_column(sa.Column('time_basis', sa.String(length=32), server_default='SERVER_RECEIVE_TIME_MAPPED', nullable=False))
        batch_op.add_column(sa.Column('t_uncertainty_s', sa.Float(), nullable=True))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provenance', sa.String(length=24), nullable=True))

    # ### end Alembic commands ###
    # Existing sessions get an explicit provenance from their mode; no
    # recording is promoted to PHYSICAL_REGISTERED by this migration (no
    # LIVE sessions can exist before device registration did).
    op.execute("UPDATE sessions SET provenance = 'SIMULATED' WHERE mode = 'SIMULATED' AND provenance IS NULL")
    op.execute("UPDATE sessions SET provenance = 'PHYSICAL_UNVERIFIED' "
               "WHERE mode = 'UNVERIFIED' AND provenance IS NULL")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('provenance')

    with op.batch_alter_table('session_markers', schema=None) as batch_op:
        batch_op.drop_column('t_uncertainty_s')
        batch_op.drop_column('time_basis')
        batch_op.drop_column('source')
        batch_op.drop_column('kind')

    with op.batch_alter_table('session_labels', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_labels_confirmed_by_users', type_='foreignkey')
        batch_op.drop_column('confirmed_at')
        batch_op.drop_column('confirmed_by')
        batch_op.drop_column('tier')

    with op.batch_alter_table('sensor_sample_chunks', schema=None) as batch_op:
        batch_op.drop_column('packet_log')
        batch_op.drop_column('firmware_version')
        batch_op.drop_column('device_t0')

    op.drop_table('recordings')
    # ### end Alembic commands ###
