"""device revocation and expiry, recording artifacts

Revision ID: 6025cd723cb5
Revises: 5e144fc9d453
Create Date: 2026-10-06 18:10:21.030316
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '6025cd723cb5'
down_revision = '5e144fc9d453'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recording_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('storage_uri', sa.String(length=500), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('export_version', sa.String(length=32), nullable=True),
    sa.Column('deidentified', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recording_id'], ['recordings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recording_artifacts', schema=None) as batch_op:
        batch_op.create_index('ix_artifact_recording_kind', ['recording_id', 'kind'], unique=False)

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('key_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('key_expires_at')
        batch_op.drop_column('revoked_at')

    with op.batch_alter_table('recording_artifacts', schema=None) as batch_op:
        batch_op.drop_index('ix_artifact_recording_kind')

    op.drop_table('recording_artifacts')
    # ### end Alembic commands ###
