"""hardware v2 sensing and ml

Revision ID: 75b9b8c873bd
Revises: d0a86de72a63
Create Date: 2026-10-06 11:50:27.934171
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '75b9b8c873bd'
down_revision = 'd0a86de72a63'
branch_labels = None
depends_on = None


# Audit actions the PostgreSQL enum type is missing. Earlier migrations added
# USER_LOGIN_FAILED etc. to the Python enum without extending the native
# type; SQLite does not enforce it, PostgreSQL rejects the insert. Added here
# idempotently.
_AUDIT_VALUES = (
    "USER_LOGIN_FAILED", "USER_LOGIN_BLOCKED", "USER_LOGOUT", "PATIENT_ASSIGNED",
    "CALIBRATION_RECORDED", "SESSION_LABEL_CREATED", "SESSION_LABEL_DELETED",
    "BASELINE_SET", "CONSENT_RECORDED", "CONSENT_REVOKED", "DATASET_EXPORTED",
    "RAW_SAMPLES_PURGED", "MODEL_REGISTERED",
)


def _extend_audit_enum() -> None:
    bind = op.get_bind()
    if bind.dialect.name != "postgresql":
        return
    # ALTER TYPE ... ADD VALUE cannot run inside a transaction block on
    # older PostgreSQL versions.
    with op.get_context().autocommit_block():
        for value in _AUDIT_VALUES:
            op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")


def upgrade() -> None:
    _extend_audit_enum()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('task', sa.String(length=40), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('artifact_path', sa.String(length=500), nullable=False),
    sa.Column('model_sha256', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=32), nullable=False),
    sa.Column('preprocessing_version', sa.String(length=32), nullable=False),
    sa.Column('dataset', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('training_config', sa.JSON(), nullable=False),
    sa.Column('validation_status', sa.JSON(), nullable=False),
    sa.Column('trained_at', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_name_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_name'), ['name'], unique=False)

    op.create_table('data_use_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.Enum('MODEL_TRAINING', name='consentscope'), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recorded_by', sa.Integer(), nullable=True),
    sa.Column('document_ref', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recorded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_use_consents', schema=None) as batch_op:
        batch_op.create_index('ix_consent_patient_scope', ['patient_id', 'scope'], unique=False)

    op.create_table('patient_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('exercise_type', sa.String(length=40), nullable=False),
    sa.Column('source_session_ids', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_baselines', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_patient_active', ['patient_id', 'active'], unique=False)

    op.create_table('activity_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('OK', 'LOW_CONFIDENCE', 'INSUFFICIENT_DATA', 'MODEL_UNAVAILABLE', name='inferencestatus'), nullable=False),
    sa.Column('activity', sa.String(length=40), nullable=True),
    sa.Column('candidate', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('probabilities', sa.JSON(), nullable=True),
    sa.Column('model_ref', sa.String(length=80), nullable=True),
    sa.Column('model_version_id', sa.Integer(), nullable=True),
    sa.Column('inference_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['model_version_id'], ['model_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_results', schema=None) as batch_op:
        batch_op.create_index('ix_activity_session_t', ['session_id', 't_start'], unique=False)

    op.create_table('device_calibrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PASS', 'WARN', 'FAIL', 'SKIPPED', name='calibrationoutcome'), nullable=False),
    sa.Column('quality', sa.Float(), nullable=True),
    sa.Column('sampling_rate_declared', sa.Float(), nullable=True),
    sa.Column('sampling_rate_measured', sa.Float(), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('calibration_version', sa.String(length=32), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_calibrations', schema=None) as batch_op:
        batch_op.create_index('ix_devcal_device_created', ['device_pk', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_calibrations_session_id'), ['session_id'], unique=False)

    op.create_table('movement_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('WINDOW', 'SESSION', name='assessmentkind'), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('mqi', sa.Float(), nullable=True),
    sa.Column('mqi_confidence', sa.Float(), nullable=True),
    sa.Column('asymmetry_score', sa.Float(), nullable=True),
    sa.Column('asymmetry_confidence', sa.Float(), nullable=True),
    sa.Column('bilateral', sa.JSON(), nullable=True),
    sa.Column('force_motion', sa.JSON(), nullable=True),
    sa.Column('phase', sa.JSON(), nullable=True),
    sa.Column('quality', sa.JSON(), nullable=True),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movement_assessments', schema=None) as batch_op:
        batch_op.create_index('ix_assessment_session_t', ['session_id', 't_start'], unique=False)

    op.create_table('repetition_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('rep_index', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_peak', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('rom_proxy_deg', sa.Float(), nullable=False),
    sa.Column('peak_velocity_dps', sa.Float(), nullable=True),
    sa.Column('smoothness_sparc', sa.Float(), nullable=True),
    sa.Column('force_peak', sa.Float(), nullable=True),
    sa.Column('force_peak_lag_s', sa.Float(), nullable=True),
    sa.Column('phase_durations', sa.JSON(), nullable=True),
    sa.Column('detector_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'side', 'rep_index', name='uq_hw_rep')
    )
    with op.batch_alter_table('repetition_results', schema=None) as batch_op:
        batch_op.create_index('ix_hw_rep_session_t', ['session_id', 't_start'], unique=False)

    op.create_table('session_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('labeller_id', sa.Integer(), nullable=True),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('exercise_type', sa.String(length=40), nullable=True),
    sa.Column('activity', sa.String(length=40), nullable=True),
    sa.Column('repetition_index', sa.Integer(), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('movement_phase', sa.String(length=16), nullable=True),
    sa.Column('quality_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['labeller_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_labels', schema=None) as batch_op:
        batch_op.create_index('ix_label_session_t', ['session_id', 't_start'], unique=False)

    op.create_table('sensor_sample_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('t_start', sa.Float(), nullable=False),
    sa.Column('t_end', sa.Float(), nullable=False),
    sa.Column('n_samples', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('encoding', sa.String(length=32), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('calibration_id', sa.Integer(), nullable=True),
    sa.Column('simulated', sa.Boolean(), nullable=False),
    sa.Column('retain_for_training', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['calibration_id'], ['device_calibrations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'chunk_index', name='uq_chunk_per_session')
    )
    with op.batch_alter_table('sensor_sample_chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_expiry', ['expires_at', 'retain_for_training'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_sample_chunks_session_id'), ['session_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('protocol_version', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # PostgreSQL cannot drop enum values; the added audit actions remain.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('protocol_version')

    with op.batch_alter_table('sensor_sample_chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensor_sample_chunks_session_id'))
        batch_op.drop_index('ix_chunk_expiry')

    op.drop_table('sensor_sample_chunks')
    with op.batch_alter_table('session_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_label_session_t')

    op.drop_table('session_labels')
    with op.batch_alter_table('repetition_results', schema=None) as batch_op:
        batch_op.drop_index('ix_hw_rep_session_t')

    op.drop_table('repetition_results')
    with op.batch_alter_table('movement_assessments', schema=None) as batch_op:
        batch_op.drop_index('ix_assessment_session_t')

    op.drop_table('movement_assessments')
    with op.batch_alter_table('device_calibrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_calibrations_session_id'))
        batch_op.drop_index('ix_devcal_device_created')

    op.drop_table('device_calibrations')
    with op.batch_alter_table('activity_results', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_session_t')

    op.drop_table('activity_results')
    with op.batch_alter_table('patient_baselines', schema=None) as batch_op:
        batch_op.drop_index('ix_baseline_patient_active')

    op.drop_table('patient_baselines')
    with op.batch_alter_table('data_use_consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consent_patient_scope')

    op.drop_table('data_use_consents')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_name'))

    op.drop_table('model_versions')
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        # drop_table leaves native enum types behind; a re-upgrade would then
        # fail with "type already exists".
        for enum_name in ("consentscope", "inferencestatus", "calibrationoutcome", "assessmentkind"):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
