"""initial schema

Revision ID: 9e47091dbc5f
Revises: 
Create Date: 2026-09-07 03:59:43.095864
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '9e47091dbc5f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.Enum('HARDWARE', 'SIMULATOR', name='devicekind'), nullable=False),
    sa.Column('leg', sa.Enum('LEFT', 'RIGHT', name='leg'), nullable=True),
    sa.Column('firmware_version', sa.String(length=40), nullable=True),
    sa.Column('protocol_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('UNKNOWN', 'ONLINE', 'OFFLINE', name='devicestatus'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sample_rate_hz', sa.Float(), nullable=True),
    sa.Column('battery_level', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_id'), ['device_id'], unique=True)

    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.Enum('WALK', 'SQUAT', 'SIT_TO_STAND', 'STEP_UP', 'SINGLE_LEG_BALANCE', 'KNEE_EXTENSION', name='exercisetype'), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('movement_type', sa.Enum('GAIT', 'REPETITION', 'HOLD', name='movementtype'), nullable=False),
    sa.Column('supported_metrics', sa.JSON(), nullable=False),
    sa.Column('phases', sa.JSON(), nullable=False),
    sa.Column('cue', sa.Text(), nullable=True),
    sa.Column('demo_asset', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('preferred_name', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('PATIENT', 'PHYSIOTHERAPIST', 'TECHNICIAN', 'ADMIN', name='role'), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('USER_REGISTERED', 'USER_LOGIN', 'PATIENT_CREATED', 'PATIENT_UPDATED', 'SESSION_STARTED', 'SESSION_ENDED', 'SESSION_CANCELLED', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'REPORT_GENERATED', 'REPORT_SHARED', 'REPORT_SHARE_REVOKED', 'NOTE_UPDATED', 'RISK_FLAG_ACKNOWLEDGED', 'PLAN_PUBLISHED', name='auditaction'), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('preferred_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=16), nullable=True),
    sa.Column('operated_leg', sa.Enum('LEFT', 'RIGHT', name='leg'), nullable=False),
    sa.Column('surgery_date', sa.Date(), nullable=True),
    sa.Column('recovery_start', sa.Date(), nullable=True),
    sa.Column('clinic_id', sa.String(length=64), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_user_id'), ['user_id'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_pk', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('IMU', 'FSR', name='sensortype'), nullable=False),
    sa.Column('location', sa.Enum('THIGH', 'SHIN', 'FOOT', name='sensorlocation'), nullable=False),
    sa.Column('capability', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('UNKNOWN', 'OK', 'DEGRADED', 'ABSENT', name='sensorstatus'), nullable=False),
    sa.Column('calibration_state', sa.String(length=24), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_pk'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_device_pk'), ['device_pk'], unique=False)

    op.create_table('exercise_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('authored_by', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=140), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='planstatus'), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['authored_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_plans_patient_id'), ['patient_id'], unique=False)

    op.create_table('patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('clinician_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ENDED', name='assignmentstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_assignments_clinician_id'), ['clinician_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_assignments_patient_id'), ['patient_id'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('exercise_type', sa.Enum('WALK', 'SQUAT', 'SIT_TO_STAND', 'STEP_UP', 'SINGLE_LEG_BALANCE', 'KNEE_EXTENSION', name='exercisetype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('mode', sa.Enum('LIVE', 'SIMULATED', 'UNKNOWN', name='sessionmode'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_pain', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('calibration_state', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETE', 'FAILED', name='calibrationstate'), nullable=False),
    sa.Column('calibration_quality', sa.Float(), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.JSON(), nullable=True),
    sa.Column('data_quality', sa.JSON(), nullable=True),
    sa.Column('analytics_version', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_status'), ['status'], unique=False)

    op.create_table('exercise_plan_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_sessions_per_week', sa.Integer(), nullable=True),
    sa.Column('target_rom_deg', sa.Float(), nullable=True),
    sa.Column('clinician_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['exercise_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exercise_plan_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exercise_plan_items_plan_id'), ['plan_id'], unique=False)

    op.create_table('metric_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_offset', sa.Float(), nullable=False),
    sa.Column('left_knee_angle_deg', sa.Float(), nullable=True),
    sa.Column('right_knee_angle_deg', sa.Float(), nullable=True),
    sa.Column('rom_running_deg', sa.Float(), nullable=True),
    sa.Column('cadence_spm', sa.Float(), nullable=True),
    sa.Column('symmetry_index_pct', sa.Float(), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('recovery_confidence', sa.Float(), nullable=True),
    sa.Column('score_contributions', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metric_snapshots_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_metric_snapshots_ts'), ['ts'], unique=False)

    op.create_table('rep_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_offset', sa.Float(), nullable=False),
    sa.Column('leg', sa.Enum('LEFT', 'RIGHT', name='leg'), nullable=False),
    sa.Column('rep_index', sa.Integer(), nullable=False),
    sa.Column('rom_deg', sa.Float(), nullable=False),
    sa.Column('peak_angle_deg', sa.Float(), nullable=True),
    sa.Column('min_angle_deg', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('smoothness', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'leg', 'rep_index', name='uq_rep_per_leg')
    )
    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rep_events_session_id'), ['session_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('baseline_session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('SESSION_SUMMARY', 'PROGRESS_COMPARISON', 'PATIENT_SUMMARY', 'CLINICIAN_REPORT', name='reportkind'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'READY', 'FAILED', name='reportstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by', sa.Integer(), nullable=True),
    sa.Column('analytics_version', sa.String(length=32), nullable=True),
    sa.Column('report_version', sa.String(length=32), nullable=False),
    sa.Column('payload_patient', sa.JSON(), nullable=True),
    sa.Column('payload_clinician', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['baseline_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_reports_patient_id'), ['patient_id'], unique=False)

    op.create_table('risk_flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('t_offset', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='riskseverity'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('source_metric', sa.String(length=64), nullable=True),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_flags_session_id'), ['session_id'], unique=False)

    op.create_table('session_device_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('leg', sa.Enum('LEFT', 'RIGHT', name='leg'), nullable=False),
    sa.Column('state', sa.Enum('CONNECTING', 'CONNECTED', 'DEGRADED', 'DISCONNECTED', name='connectionstate'), nullable=False),
    sa.Column('first_connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('packets_received', sa.Integer(), nullable=False),
    sa.Column('packets_dropped', sa.Integer(), nullable=False),
    sa.Column('sequence_gaps', sa.Integer(), nullable=False),
    sa.Column('connected_seconds', sa.Float(), nullable=False),
    sa.Column('fsr_available', sa.Boolean(), nullable=False),
    sa.Column('calibration_state', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETE', 'FAILED', name='calibrationstate'), nullable=False),
    sa.Column('signal_quality', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'leg', name='uq_session_leg')
    )
    with op.batch_alter_table('session_device_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_device_links_session_id'), ['session_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SESSION_COMPLETED', 'REPORT_READY', 'DEVICE_CONNECTED', 'DEVICE_DISCONNECTED', 'SIGNAL_QUALITY_LOW', 'NEW_RISK_FLAG', 'REVIEW_RECOMMENDED', 'PROGRESS_MILESTONE', 'EXERCISE_PLAN_UPDATED', name='notificationtype'), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='notificationseverity'), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('related_patient_id', sa.Integer(), nullable=True),
    sa.Column('related_session_id', sa.Integer(), nullable=True),
    sa.Column('related_report_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_dedupe_key'), ['dedupe_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_notifications_recipient_id'), ['recipient_id'], unique=False)

    op.create_table('report_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('include_clinician_sections', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report_shares', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_shares_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_shares_token_hash'), ['token_hash'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_shares', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_shares_token_hash'))
        batch_op.drop_index(batch_op.f('ix_report_shares_report_id'))

    op.drop_table('report_shares')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_recipient_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_dedupe_key'))

    op.drop_table('notifications')
    with op.batch_alter_table('session_device_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_device_links_session_id'))

    op.drop_table('session_device_links')
    with op.batch_alter_table('risk_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_flags_session_id'))

    op.drop_table('risk_flags')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_patient_id'))
        batch_op.drop_index(batch_op.f('ix_reports_idempotency_key'))

    op.drop_table('reports')
    with op.batch_alter_table('rep_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rep_events_session_id'))

    op.drop_table('rep_events')
    with op.batch_alter_table('metric_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_ts'))
        batch_op.drop_index(batch_op.f('ix_metric_snapshots_session_id'))

    op.drop_table('metric_snapshots')
    with op.batch_alter_table('exercise_plan_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_plan_items_plan_id'))

    op.drop_table('exercise_plan_items')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_idempotency_key'))

    op.drop_table('sessions')
    with op.batch_alter_table('patient_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_assignments_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_assignments_clinician_id'))

    op.drop_table('patient_assignments')
    with op.batch_alter_table('exercise_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exercise_plans_patient_id'))

    op.drop_table('exercise_plans')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_device_pk'))

    op.drop_table('sensors')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_user_id'))
        batch_op.drop_index(batch_op.f('ix_patients_clinic_id'))

    op.drop_table('patients')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('exercises')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_device_id'))

    op.drop_table('devices')
    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        # drop_table leaves native enum types behind; without this a
        # downgrade followed by an upgrade fails ("type ... already exists").
        for enum_name in ('assignmentstatus', 'auditaction', 'calibrationstate', 'connectionstate', 'devicekind', 'devicestatus', 'exercisetype', 'leg', 'movementtype', 'notificationseverity', 'notificationtype', 'planstatus', 'reportkind', 'reportstatus', 'riskseverity', 'role', 'sensorlocation', 'sensorstatus', 'sensortype', 'sessionmode', 'sessionstatus'):
            op.execute(f"DROP TYPE IF EXISTS {enum_name}")
