"""social sign-in identities, single-use oauth state, optional password

Revision ID: cf12f69e0b50
Revises: 6025cd723cb5
Create Date: 2026-10-07 04:43:55.237958

Google / Facebook sign-in. A user's external sign-in identities live in
user_identities, keyed by (provider, provider_subject) -- never by email.
oauth_state_uses makes every OAuth state single-use across API instances.
users.password_hash becomes optional: an account created through a provider
may have no password (password sign-in then fails like a wrong password).

On PostgreSQL the native auditaction type gains the new action values
(ALTER TYPE ... ADD VALUE, which cannot run inside a transaction block).
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'cf12f69e0b50'
down_revision = '6025cd723cb5'
branch_labels = None
depends_on = None


_NEW_AUDIT_ACTIONS = ("IDENTITY_LINKED", "IDENTITY_UNLINKED", "OAUTH_LOGIN",
                      "OAUTH_LOGIN_REFUSED", "USER_DELETED")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            for value in _NEW_AUDIT_ACTIONS:
                op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_state_uses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_hash', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('state_hash')
    )
    with op.batch_alter_table('oauth_state_uses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_oauth_state_uses_used_at'), ['used_at'], unique=False)

    op.create_table('user_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_subject', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=254), nullable=True),
    sa.Column('provider_email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("provider IN ('google', 'facebook', 'phone')", name='ck_identity_provider'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_subject', name='uq_identity_provider_subject'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_identity_user_provider')
    )
    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_identities_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Accounts created through Google or Facebook have no password, so the
    # column cannot become NOT NULL again without inventing one. Refuse.
    remaining = op.get_bind().execute(
        sa.text("SELECT COUNT(*) FROM users WHERE password_hash IS NULL")).scalar()
    if remaining:
        raise RuntimeError(f"{remaining} account(s) have no password (created through Google or "
                           "Facebook); delete them or set passwords before downgrading.")
    # PostgreSQL cannot drop enum values; the extra auditaction values stay, unused.

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('user_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_identities_user_id'))

    op.drop_table('user_identities')
    with op.batch_alter_table('oauth_state_uses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_oauth_state_uses_used_at'))

    op.drop_table('oauth_state_uses')
    # ### end Alembic commands ###
