"""recovery focus blocks, events and reminders

Revision ID: d0a86de72a63
Revises: fbafc9e00f74
Create Date: 2026-09-08 00:33:41.517081
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'd0a86de72a63'
down_revision = 'fbafc9e00f74'
branch_labels = None
depends_on = None


def _has(table: str) -> bool:
    from alembic import op as _op

    return table in sa.inspect(_op.get_bind()).get_table_names()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('focus_reminders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=5), nullable=False),
    sa.Column('weekdays', sa.String(length=20), nullable=False),
    sa.Column('timezone_name', sa.String(length=64), nullable=False),
    sa.Column('target_duration_s', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.Enum('WALK', 'SQUAT', 'SIT_TO_STAND', 'STEP_UP', 'SINGLE_LEG_BALANCE', 'KNEE_EXTENSION', name='exercisetype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_reminders_patient_id'), ['patient_id'], unique=False)

    op.create_table('focus_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('target_duration_s', sa.Integer(), nullable=False),
    sa.Column('exercise_type', sa.Enum('WALK', 'SQUAT', 'SIT_TO_STAND', 'STEP_UP', 'SINGLE_LEG_BALANCE', 'KNEE_EXTENSION', name='exercisetype'), nullable=False),
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('READY', 'ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', 'INTERRUPTED', name='focusstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_sessions_local_date'), ['local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_focus_sessions_status'), ['status'], unique=False)

    op.create_table('focus_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('focus_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('STARTED', 'PAUSED', 'RESUMED', 'COMPLETED', 'CANCELLED', 'INTERRUPTED', name='focuseventkind'), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['focus_id'], ['focus_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('focus_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_focus_events_focus_id'), ['focus_id'], unique=False)

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('focus_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sessions_focus_id'), ['focus_id'], unique=False)
        # SQLite batch mode rebuilds the table, and a rebuilt constraint must
        # be named or it cannot be referenced on downgrade.
        batch_op.create_foreign_key(
            'fk_sessions_focus_id', 'focus_sessions', ['focus_id'], ['id'], ondelete='SET NULL'
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_focus_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sessions_focus_id'))
        batch_op.drop_column('focus_id')

    with op.batch_alter_table('focus_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_events_focus_id'))

    op.drop_table('focus_events')
    with op.batch_alter_table('focus_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_sessions_status'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_focus_sessions_local_date'))

    op.drop_table('focus_sessions')
    with op.batch_alter_table('focus_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_focus_reminders_patient_id'))

    op.drop_table('focus_reminders')
    # ### end Alembic commands ###
