"""synthetic demonstration namespace, programme fields, generation metadata, session traces

Revision ID: e791f75c4f26
Revises: ec7fd4532599
Create Date: 2026-10-07 20:32:51.287373

* patients.provenance / demo_key: a generated or dataset record is marked as
  such (NULL = a real person's record), and the demonstration seed can only
  ever find, update or reset rows it created.
* patients.program / program_days / planned_sessions: the rehabilitation
  programme a clinician sets; adherence is measured against it.
* sessions.generation: how a generated or replayed session was produced
  (generator version, seed, inputs, source dataset, model, timestamp).
* session_traces: a decimated per-side movement trace kept when a hardware-v2
  session ends, so it can be replayed after raw-sample retention expires.
* reportkind MOVEMENT_PROGRESS, auditaction DEMO_DATA_SEEDED / DEMO_DATA_RESET.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e791f75c4f26'
down_revision = 'ec7fd4532599'
branch_labels = None
depends_on = None


NEW_AUDIT_ACTIONS = ("DEMO_DATA_SEEDED", "DEMO_DATA_RESET")


def upgrade() -> None:
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Enum values cannot be added inside a transaction on older servers.
        with op.get_context().autocommit_block():
            for value in NEW_AUDIT_ACTIONS:
                op.execute(f"ALTER TYPE auditaction ADD VALUE IF NOT EXISTS '{value}'")
            op.execute("ALTER TYPE reportkind ADD VALUE IF NOT EXISTS 'MOVEMENT_PROGRESS'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_traces',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('rate_hz', sa.Float(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('units', sa.JSON(), nullable=True),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('program', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('program_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planned_sessions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('provenance', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('demo_key', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_provenance'), ['provenance'], unique=False)
        batch_op.create_unique_constraint('uq_patients_demo_key', ['demo_key'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('generation')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_patients_demo_key', type_='unique')
        batch_op.drop_index(batch_op.f('ix_patients_provenance'))
        batch_op.drop_column('demo_key')
        batch_op.drop_column('provenance')
        batch_op.drop_column('planned_sessions')
        batch_op.drop_column('program_days')
        batch_op.drop_column('program')

    op.drop_table('session_traces')
    # ### end Alembic commands ###
    # PostgreSQL cannot drop an enum value; DEMO_DATA_* and MOVEMENT_PROGRESS
    # stay in their types, unused, exactly as the earlier audit additions do.
