"""live validation snapshots for multi-instance hosts

Revision ID: ec7fd4532599
Revises: cf12f69e0b50
Create Date: 2026-10-07 08:06:06.802984

Live session state lives in the memory of the API instance receiving the
device's stream. On hosts that run several instances (Vercel Fluid compute),
a dashboard's validation poll can land on another instance; the receiving
instance now writes its validation inputs here every few seconds so any
instance can answer. One row per session, deleted with the session.
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'ec7fd4532599'
down_revision = 'cf12f69e0b50'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_snapshots',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('live_snapshots')
    # ### end Alembic commands ###
